### ISSUE TITLE
Failing with FLAC files

### ISSUE THREAD

**Issue by jason-a69** [brianhornsby/script.similartracks#3]
Hi Brian,

I was successfully running this script with MP3s.

I loaded up my FLAC files and it failed, the debug is below (I changed the api_key)

16:15:52 T:1488651328  NOTICE: script.similartracks: DEBUG: Looking for similar tracks to The Rolling Stones - Around And Around
16:15:52 T:1488651328  NOTICE: script.similartracks: DEBUG: Last.fm URL: http://ws.audioscrobbler.com/2.0/?format=json&track=Around+And+Around&autocorrect=1&artist=The+Rolling+Stones&api_key=xxxxxxxxxxxxxxxxxxxxxxxxx&method=track.getsimilar
16:15:54 T:1488651328  NOTICE: script.similartracks: DEBUG: Last.fm returned 100 similar tracks
16:15:57 T:1488651328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'list' object has no attribute 'encode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.similartracks/default.py", line 201, in <module>
                                                count, playlisttracks = get_similar_tracks(artist, title)
                                              File "/storage/.kodi/addons/script.similartracks/default.py", line 134, in get_similar_tracks
                                                if 'artist' in artist and artist['artist'].encode('ascii', 'ignore') == trackartist:
                                            AttributeError: 'list' object has no attribute 'encode'
                                            -->End of Python script error report<--

My artist and my track artists are both populated in this case and set to the same value. I do not mind doing some testing to help resolve this issue.

Many thanks

Jason

**Comment by brianhornsby** [comment]
That error is weird. 
It's complaining that the value in artist['artist'] is of type list, when it should always be of type string.
It's getting that data from your Kodi library. 
In that bit of code it is going through the list of artists that are specified in your Kodi audio library to see if any match the artists returned from last.fm.

Is it possible for you to edit the default.py file and add ```print artist['artist']```in the line before the if statement (line #134)?

**Comment by jason-a69** [comment]
I'll give that a go on Monday, I'm away from my pi until then.
Thanks for taking a look

**Comment by jason-a69** [comment]
It's my fault, I found some dodgy artist data in my library

12:07:58 T:1642067008  NOTICE: [u'Cond. Denis King', u'The South Bank Orchestra Cond. By Denis King']

What I did was to put in a test to make sure artist['artist'] is a string
So the code looks like this

        for artist in artists:
            if isinstance(artist['artist'], str) or isinstance(artist['artist'], unicode):
                if 'artist' in artist and artist['artist'].encode('ascii', 'ignore') == trackartist:
                    artistid = artist['id']
                    break

For some strange reason, I still cannot get it to work with Angie by The Rolling Stones :(

I get this

08:11:46 T:1563423808  NOTICE: script.similartracks: DEBUG: Last.fm URL: http://ws.audioscrobbler.com/2.0/?format=json&track=Angie&autocorrect=1&artist=The+Rolling+Stones+&api_key=XXXXXX&method=track.getsimilar
08:11:46 T:1563423808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('similartracks',)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.similartracks/default.py", line 202, in <module>
                                                count, playlisttracks = get_similar_tracks(artist, title)
                                              File "/storage/.kodi/addons/script.similartracks/default.py", line 105, in get_similar_tracks
                                                lastfmtracks = get_lastfm_similar_tracks(artist, title)
                                              File "/storage/.kodi/addons/script.similartracks/default.py", line 97, in get_lastfm_similar_tracks
                                                for track in json_response['similartracks']['track']:
                                            KeyError: ('similartracks',)
                                            -->End of Python script error report<--

So...one step forwards and another step back!

**Comment by brianhornsby** [comment]
That error would seem to indicate that the JSON response from Last.fm didn't contain either the 'similartracks' or 'track' key

**Comment by jason-a69** [comment]
Probably best to check the variables that are not under your control.
