### ISSUE TITLE
How to add similar tracks from the play screen?

### ISSUE THREAD

**Issue by a3igner** [brianhornsby/script.similartracks#6]
Hello

Thanks for this plugin. I installed it. But i can only find i can add similar tracks by going to
PROGRAMM ADDONS in the ADDON menu and then Running it from inside the Plugin interface.

How can i run the script from the main menu/interface or even the play screen. 

Or have it show up as an option in the Playlist menu of the Music section.

Rgs
Andreas

**Comment by Uatschitchun** [comment]
You can add a shortcut to the main menu depending on the skin you are using.
Else you might assign a key on the remote
